"""added password field

Revision ID: 056e8ed64eab
Revises: 841809a727cb
Create Date: 2025-06-25 11:16:18.262566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056e8ed64eab'
down_revision = '841809a727cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
