"""pic

Revision ID: 484a5e3ed586
Revises: afd3b16fba0a
Create Date: 2025-07-13 10:47:43.569694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484a5e3ed586'
down_revision = 'afd3b16fba0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
