"""about author

Revision ID: 79a9ed333ab7
Revises: e51dac300eb9
Create Date: 2025-07-12 14:27:08.438694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a9ed333ab7'
down_revision = 'e51dac300eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(length=500), nullable=True))
        batch_op.add_column(sa.Column('user_type', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_type')
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
